const data = [
  {
    "Tag Name": "MD-LT-35012",
    "Tag Description/Service":
      "7148-Level Transmitter, Mag. Follow - MAK-3501 TG NO.1 FUEL GAS SEPARATOR",
    "Tag Type": "Instrumentation",
    "Functional Class": "Level Device",
    "Physical Class": "Level Device, Magnetic Follower",
    "Document Number": "0304-4661-11",
  },
  {
    "Tag Name": "MD-DSN-5252-06",
    "Tag Description/Service": "5KV FUSE DISCONNECT - SWITCH",
    "Tag Type": "Electrical",
    "Functional Class": "Switch",
    "Physical Class": "Switch, Disconnect",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-DSN-5252-08",
    "Tag Description/Service": "5KV FUSE DISCONNECT - SWITCH",
    "Tag Type": "Electrical",
    "Functional Class": "Switch",
    "Physical Class": "Switch, Disconnect",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-DSN-5252-10",
    "Tag Description/Service": "5KV FUSE DISCONNECT - SWITCH",
    "Tag Type": "Electrical",
    "Functional Class": "Switch",
    "Physical Class": "Switch, Disconnect",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-DSN-5252-12",
    "Tag Description/Service": "5KV FUSE DISCONNECT - SWITCH",
    "Tag Type": "Electrical",
    "Functional Class": "Switch",
    "Physical Class": "Switch, Disconnect",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-EGD-5090",
    "Tag Description/Service": "EMERGENCY GENERATOR - DRIVER",
    "Tag Type": "Mechanical",
    "Functional Class": "Driver",
    "Physical Class": "Driver, Reciprocating Engine",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-HRN-5300-A",
    "Tag Description/Service": "TRANSFORMER GROUNDING - RESISTOR",
    "Tag Type": "Electrical",
    "Functional Class": "Resistor",
    "Physical Class": "Resistor, Grounding",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-HRN-5300-B",
    "Tag Description/Service": "TRANSFORMER GROUNDING - RESISTOR",
    "Tag Type": "Electrical",
    "Functional Class": "Resistor",
    "Physical Class": "Resistor, Grounding",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-HRS-5310-A",
    "Tag Description/Service": "TRANSFORMER GROUNDING - RESISTOR",
    "Tag Type": "Electrical",
    "Functional Class": "Resistor",
    "Physical Class": "Resistor, Grounding",
    "Document Number": "1430-20-EL-DG-6010",
  },
  {
    "Tag Name": "MD-JT-50002",
    "Tag Description/Service":
      "7460-Power Transmitter - MD-GNN-5000 KW OUTPUT CAP. TO LOAD SHED",
    "Tag Type": "Instrumentation",
    "Functional Class": "Indicator",
    "Physical Class": "Indicator, Level",
    "Document Number": "1430-20-EL-DG-6015",
  },
  {
    "Tag Name": "MD-XA-525002C",
    "Tag Description/Service": "SGN-5250 SWGR BKN-5250-02 STATUS TO LOAD SHED",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-XA-525002D",
    "Tag Description/Service": "SGN-5250 5KV SWGR BKN-5250-02 RELAY FAILURE",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-XA-525004B",
    "Tag Description/Service": "SGN-5350 SWITCHGEAR BKN-5250-04 STATUS",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-XA-525004C",
    "Tag Description/Service": "SGN-5250 SWGR BKN-5250-04 STATUS TO LOAD SHED",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-XA-525004D",
    "Tag Description/Service": "SGN-5250 5KV SWGR BKN-5250-04 RELAY FAILURE",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-XA-52501",
    "Tag Description/Service": "GNN-5000 TURBINE GEN CONTROL POWER",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Status",
    "Document Number": "1430-20-EL-DG-6015",
    INSTR_TYPE: "7500-Status",
    EQUIPMENT: " ",
    LINE: " ",
  },
  {
    "Tag Name": "MD-PDI-48401",
    "Tag Description/Service":
      "GAS CORROSION INH PBE-4840 FILTER DIFF PRESSURE",
    "Tag Type": "Instrumentation",
    "Functional Class": "Control System",
    "Physical Class": "Control System, Indication",
    "Document Number": "1430-20-PI-DG-4585",
    INSTR_TYPE: "7500-Indication",
    EQUIPMENT: "PBE-4840",
    LINE: " ",
  },
];

export default data;
